= Security Workshop 

The current repository contains top 10 Web Application Security Risks examples.

* https://owasp.org/www-project-top-ten[OWASP Top 10]
* https://github.com/aglumova/web-security-workshop/blob/main/presentation/Hack_Your_Code.pdf[Hack Your Code Presentation]
* https://github.com/aglumova/web-security-workshop/blob/main/presentation/Hack_Yourself_First.pdf[Hack Yourself First Presentation]
* https://github.com/aglumova/web-security-workshop/blob/main/task/ws-task.md[Workshop Task]

== Requirements to run tests on Java

* Docker
* Java 11+

== Injection flaws

Injection flaws result from a classic failure to filter untrusted input. It can happen when you pass unfiltered data to the SQL server (SQL injection), to the browser (XSS), to the LDAP server (LDAP injection), or anywhere else. The problem here is that the attacker can inject commands to these entities, resulting in loss of data and hijacking clients’ browsers.
Anything that your application receives from untrusted sources must be filtered, preferably according to a whitelist. You should almost never use a blacklist, as getting that right is very hard and usually easy to bypass. Antivirus software products typically provide stellar examples of failing blacklists. Pattern matching does not work.

=== SQL Injection

==== Examples

* https://github.com/aglumova/web-security-workshop/tree/main/src/test/java/com/aglumova/ws/injection/sql[SQL Injection]

==== References

* https://www.owasp.org/index.php/SQL_Injection[SQL Injection] (OWASP)
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.md[SQL Injection Prevention Cheat Sheet]

=== LDAP Injection

==== Examples

* https://github.com/aglumova/web-security-workshop/tree/main/src/test/java/com/aglumova/ws/injection/ldap[LDAP Injection]

==== References

* https://owasp.org/www-community/attacks/LDAP_Injection[LDAP Injection] (OWASP)
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/LDAP_Injection_Prevention_Cheat_Sheet.md[LDAP Injection Prevention Cheat Sheet]

== Broken Authentication

This is a collection of multiple problems that might occur during broken authentication, but they don’t all stem from the same root cause.

Possible pitfalls:

- The URL might contain the session id and leak it in the referer header to someone else.
- The passwords might not be encrypted either in storage or transit.
- The session ids might be predictable, thus gaining access is trivial.
- Session hijacking might be possible, timeouts not implemented right or using HTTP (no SSL security).
- etc.

*Session hijacking*

Session hijacking, also known as session fixation, is a neat exploit. It relies on the fact that HTTP is a stateless protocol and users must identify themselves to servers on every request with a shared session id, which is typically stored as a cookie. The core of the attack relies on obtaining that session id and then setting your own session id to that value. This lets you "steal" another user's session and impersonate them.

*Three common protection strategies against session fixation*

- *Only use HTTPS*

This is a viable strategy and is used by many popular websites. For example, Facebook will now only serve you pages via HTTPS, which prevents any fixation from happening as all traffic is encrypted (including the session id) and cannot be decoded by a third party. Of course, this has the downside that all traffic must be served via HTTPS, which increases processing overhead, network traffic, and makes caches much less effective. For many sites that deal with sensitive information, this is an acceptable cost.

- *Once a user logs in, enforce HTTPS for future traffic.*

This is the most popular mechanism to prevent hijacking. With this strategy, you concede to showing users pages via HTTP as you normally would. However, once they authenticate, you invalidate their previous HTTP session and switch over to an HTTPS session. This means that every single page they see after they login must be HTTPS.

- *Secure HTTPS traffic with a secondary cookie*

An excellent compromise between encrypting everything and encrypting nothing. We begin by establishing a normal HTTP session for a user when they first visit the site and allow them to view pages over HTTP. However, as soon as the user sees an HTTPS page, we set a secondary, HTTPS session id cookie without invalidating their previous session. Once the HTTPS cookie is set, every time that user requests an HTTPS, we validate not only the normal session id cookie, but also the secondary one. Therefore, a session hijacker would not be able to see any information that is served through HTTPS, as all sensitive information and actions should be!

=== Examples

** https://github.com/aglumova/web-security-workshop/tree/main/src/test/java/com/aglumova/ws/authentication[Authentication]

=== References

* https://auth0.com/blog/what-is-broken-authentication/[Broken Authentication]
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Authentication_Cheat_Sheet.md[Authentication Cheat Sheet]

== Sensitive Data Exposure

=== Examples

** https://github.com/aglumova/web-security-workshop/tree/main/src/test/java/com/aglumova/ws/sensitive[Sensitive Data]

=== References

* https://thehackerish.com/sensitive-data-exposure-explained-owasp-top-10-vulnerabilities/[Sensitive Data Exposure]

== Broken Access Control

=== Examples

TBD

=== References

* https://owasp.org/www-community/Broken_Access_Control[Broken Access Control]
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Access_Control_Cheat_Sheet.md[Access Control Cheat Sheet]

== Security Misconfiguration

=== Examples

TBD

=== References

* https://thehackerish.com/owasp-security-misconfiguration-explained/[Security Misconfiguration]
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Database_Security_Cheat_Sheet.md[Database Security Cheat Sheet]
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Microservices_security.md[Microservice Security Cheat Sheet]
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/REST_Security_Cheat_Sheet.md[REST Security Cheat Sheet]

== Cross-Site Scripting (XSS)

=== Examples

** https://github.com/aglumova/web-security-workshop/tree/main/src/test/resources/xss[XSS Example]

=== References

* https://owasp.org/www-community/attacks/xss/[Cross-Site Scripting (XSS)] (OWASP)
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.md[Cross Site Scripting Prevention Cheat Sheet]

== Insecure Deserialization

=== Examples

** https://github.com/aglumova/web-security-workshop/tree/main/src/test/java/com/aglumova/ws/deserialization[Insecure Deserialization Example]

=== References

* https://owasp.org/www-pdf-archive/GOD16-Deserialization.pdf[Insecure Deserialization] (OWASP)
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Deserialization_Cheat_Sheet.md[Insecure Deserialization Cheat Sheet]

== Insecure Direct Object References

=== Examples

TBD

=== References

* https://owasp.org/www-chapter-ghana/assets/slides/IDOR.pdf[Insecure Direct Object References] (OWASP)
* https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/Insecure_Direct_Object_Reference_Prevention_Cheat_Sheet.md[Insecure Direct Object Reference Prevention Cheat Sheet]
